### PR TITLE
[ extractors.xml ] [ config ] [ Resources ] Added service for ExtrasExtractor

### PR DESCRIPTION
**Pull request by maxlipsky**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Did we forget that? 
Will have a closer look tonight. 
@dbu we have to merge that from an early version to the top, right?

**Comment by dbu** [comment]
if you want this in 1.3 as well then yes. i guess the easiest if you want to do that is adding the repo of maxlipsky as additional remote in your checkout of seo bundle, then checkout the 1.3 branch (from origin) and cherry-pick the commit of this PR into the 1.3 branch. and merge 1.3 into master.

**Comment by dbu** [comment]
@ElectricMaxxx can you wrap this up please? looks like there is now a conflict too

**Comment by ElectricMaxxx** [comment]
@dbu i added the milestone, that we won't forget it.

**Comment by ElectricMaxxx** [comment]
closed in favor of #319 thanks @maxlipsky

**Pull request closed without merging**
