### PR TITLE
[WCM] Support tabs in the admin extension

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
is that for #143 and what would be missing?

**Comment by dbu** [comment]
according to discussion in other places, i think this should not go into the upcoming release but only the next one, if we bump sonata to 2.4

**Comment by ElectricMaxxx** [comment]
@WouterJ you remember what is going on here?

**Comment by dbu** [comment]
i will wait with tagging this bundle until we decided on https://github.com/symfony-cmf/MenuBundle/pull/219/files/a260c0be33ee2be9656471b14372e9aae866d38a#r57954530

**Comment by ElectricMaxxx** [comment]
This should be moved into https://github.com/symfony-cmf/sonata-admin-integration-bundle

**Comment by WouterJ** [comment]
Refs https://github.com/symfony-cmf/sonata-admin-integration-bundle/issues/4

**Pull request closed without merging**
