### PR TITLE
fix build status icon

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
travis changed the url
(Same for all bundles)

### CODE REVIEW

**Comment by dbu** [comment]
ah of course, because we renamed the repos... could you do that for all the cmf bundles, maybe? push directly to master would be fine if you only change that bit.

**Comment by ElectricMaxxx** [comment]
:+1: tonight.

**Comment by ElectricMaxxx** [comment]
@dbu not at all they moved from `http://secure.` to `https://`.

**Comment by dbu** [comment]
ah ok. thanks for the fixing round!

**Pull request merged**
