### PR TITLE
Remove sonata admin

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
this PR removes all sonata admin dependencies and re-implement them in a kind of cmf sonata admin bridge/integration 

things to be merged/green:
- [x]  CmfSonataAdminIntegrationBridge
- [x] [Test on sandbox](https://github.com/symfony-cmf/cmf-sandbox/pull/332)

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Seems to be ready to review. the sandbox integration works fine.

**Comment by dbu** [comment]
is the admin bundle merged? (checkboxes are not marked)
and did you update the sandbox? we can already do that before merging this PR, so that we notice if anything is amiss.

**Comment by dbu** [comment]
and please add  an explanation to the changelog

**Comment by ElectricMaxxx** [comment]
The extracted classes are still merged in the SonataIntegration. Will have a look at the sandbox, but i think she was ok.

**Comment by ElectricMaxxx** [comment]
@wouterj @dbu you have any idea why my build is failing for specific symfony versions?

**Comment by ElectricMaxxx** [comment]
So this gonna be green in some seconds, anybody wanna review?

**Pull request merged**
