### PR TITLE
DevKit updates - Prepare Release

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
| Q             | A
| ------------- | ---
| Branch?       | "master" for new features / the branch of the current release for fixes
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
mh is stil have an issue with the ORM test, at least with enabling the db manager in the tests.

**Comment by dbu** [comment]
looks like the same problem we also see on routing-bundle

**Comment by ElectricMaxxx** [comment]
Awesome it works.

**Comment by dbu** [comment]
cheers! good job!

**Pull request merged**
